# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
    schedule:
      interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v11/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v12/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v13/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v14/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v15/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v16/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/angular/v17/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/hydrate/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/preact/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/react/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/react-standalone/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/solid/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/adapters/vue/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/components/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/create-kolibri/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/designer/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/samples/react/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/schema/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/storybook/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/themes/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/themes/bmf/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/themes/ecl/ec/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/themes/ecl/eu/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/themes/itzbund/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/tools/kolibri-cli/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly
  # - package-ecosystem: npm
  #   directory: /packages/tools/visual-tests/
  #   labels:
  #     - dependabot
  #   schedule:
  #     interval: weekly

