# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/angular/v15/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/hydrate/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/preact/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/react/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/solid/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/svelte/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/adapters/vue/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/components/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/create-kolibri/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/designer/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/slidev/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/storybook/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/themes/'
    schedule:
      interval: daily
    target-branch: main

  # deprecated
  - package-ecosystem: npm
    directory: '/packages/core/'
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: npm
    directory: '/packages/schema/'
    schedule:
      interval: daily
    target-branch: main
