name: Sync to Open CoDE

on:
  workflow_dispatch:
  schedule:
    - cron: '* 4-20/4 * * *' # von 6 bis 22 Uhr

jobs:
  sync:
    if: github.repository == 'public-ui/kolibri'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: 'main'
      - name: git-sync
        run: |
          git config pull.rebase true
          git remote add opencode https://OC000005112572:${{ secrets.GITLAB_PERSONAL_ACCESS_TOKEN }}@gitlab.opencode.de/OC000005112572/kolibri.git
          git pull opencode main
          git push opencode
